store = ['Les grillettines au blé complet',
 'Pain AMS complet',
 'GrandLait - Demi-écrémé',
 'Noir Extra',
 'Confiture Allégée Fraises',
 'Biscuits Soja Figue',
 'Mélange de fruits secs',
 'La Bûche fondante',
 'Fraise Intense',
 'Special K feuilles de Chocolat Noir (Format Maxi)',
 'Miel Pops',
 "Granola L'Original Gros Éclats de Chocolat",
 'Tartines de Pain Blé Complet ×24 Tranches',
 'Fitness nature',
 'Pains au chocolat',
 'Tomato ketchup',
 'Pepsi max zero',
 "Le supérieur cuit à l'étouffée -25%  sel* - 4 tranches",
 'Goûter aux écorces  confites',
 'belvita',
 'Monaco',
 'Planta Fin Doux (60 % MG) Tartine & Cuisson',
 "Crousti'Son Miel Sésame",
 'Coca Zéro',
 'Biscottes Équilibre',
 'Pomme pur fruit pressé',
 'Oméga 3',
 'Eau minérale gazeuse',
 'Ketchup allegé',
 "Pim's orange",
 'Tropical',
 'Margarine tartine doux',
 'BelVita Petit Déjeuner Oririnal -30 % de sucres',
 'LE PUR JUS Orange sans pulpe',
 'Pastis de Marseille',
 'Fitness Chocolat Noir',
 'Véritable Petit Beurre',
 'Fitness Chocolat Au Lait',
 "Pom'Potes (Pomme)",
 'Gaufres Miel']


upp = [x.lower().capitalize() for x in store]
print(upp)
